development:
  adapter: postgresql
  encoding: unicode
  database: explore_xdk_webapp_development
  pool: 50
  username: dbadmin
  password: dbadmin

test:
  adapter: postgresql
  encoding: unicode
  database: explore_xdk_webapp_test
  pool: 50
  username: dbadmin
  password: dbadmin

production:
  adapter: postgresql
  encoding: unicode
  database: explore_xdk_webapp_production
  pool: 50
  username: dbadmin
  password: dbadmin  
  
